### ISSUE TITLE
TS support

### ISSUE THREAD

**Issue by drawbit** [Developer-Amit/react-aws-s3#14]
Source code is typescript but the npm build is all JS.

Let me create a PR for tsconfig fix.

**Comment by drawbit** [comment]
![image](https://user-images.githubusercontent.com/20286132/106310855-3448b880-6232-11eb-9e46-e7be0ed6d034.png)


I tried microbundle and it builds out all TS files, why don't you publish TS files to npm?

**Comment by Developer-Amit** [comment]
Please check updates
