### ISSUE TITLE
Is it secure?

### ISSUE THREAD

**Issue by microspace** [Developer-Amit/react-aws-s3#25]
Is it secure to provide s3 access credentials in frontend code?

**Comment by microspace** [comment]
No, I don't think it is secure:

> When uploading files to s3 directly from front end, your AWS credentials are exposed in the network tab. Refrain from uploading files to protected S3 buckets directly from FE. Always use a server to upload files.

**Comment by ahurlburt** [comment]
Came here to question the same thing. I think the creds would be in your source files as well if they are stored client side... Too bad.

**Comment by trondhindenes** [comment]
The correct way would be to have a server component generate a signed url that is then passed to the client, and used for upload. The url functions as a short-lived credential, see https://aws.amazon.com/blogs/compute/uploading-to-amazon-s3-directly-from-a-web-or-mobile-application/.
I have no idea if react-aws-s3 supports this way of uploading.

**Comment by NoPointExc** [comment]
Check out this: [using-presigned-url](https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-presigned-url.html) to grant the client access to your S3 with pre-signed credential if you come here with the same purpose as me. The [Gateway](https://aws.amazon.com/blogs/compute/uploading-to-amazon-s3-directly-from-a-web-or-mobile-application/) works as well.
