### ISSUE TITLE
Can it automatically assume the role configured in aws sdk via instance profile?

### ISSUE THREAD

**Issue by sanudatta11** [Developer-Amit/react-aws-s3#3]

**Comment by Developer-Amit** [comment]
Hi @sanudatta11 
Yes, When you create your Access And Secret Key so this will take default IAM role from the Key access permissions. 

But still, you can setup a Custom Bucket policy as per your need find a quick sample : 
`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Example permissions",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::<aws-account-id-databricks>:role/<iam-role-for-s3-access>"
      },
      "Action": [
        "s3:GetBucketLocation",
        "s3:ListBucket"
      ],
      "Resource": "arn:aws:s3:::<s3-bucket-name>"
    },
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::<aws-account-id-databricks>:role/<iam-role-for-s3-access>"
      },
      "Action": [
        "s3:PutObject",
        "s3:GetObject",
        "s3:DeleteObject"
      ],
      "Resource": "arn:aws:s3:::<s3-bucket-name>/*"
    }
  ]
}`

You can please Visit Bucket policy setup full guide here -  https://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html
