### ISSUE TITLE
Getting error: net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by stdev321** [Developer-Amit/react-aws-s3#36]
Whenever I try to delete a file from bucket I get this type of error : TypeError: Failed to fetch
In the case of upload file, it is working fine also SDK is using different URL to hit upload and delete functions

**Comment by Lekhrajk** [comment]
i am getting same error while uploading did you find any solutions ?

**Comment by DanThemes** [comment]
It's using this format: https://BUCKET.s3**-**REGION.amazonaws.com/, while my bucket is actually located at https://BUCKET.s3**.**REGION.amazonaws.com/ (notice the dash vs dot difference). Does anyone have any solutions?

**Comment by Developer-Amit** [comment]
Can you try to pass the bucket URL in props directly?
