### ISSUE TITLE
File extension getting updated as per the file type

### ISSUE THREAD

**Issue by STNCON6RG** [Developer-Amit/react-aws-s3#5]
After selecting the file from dialog the file name is updated.
Please see the below details.
File Object:
{
	name: "test-file.txt"
	lastModified: 1570638118950
	lastModifiedDate: Wed Oct 09 2019 21:51:58 GMT+0530 (India Standard Time) {}
	webkitRelativePath: ""
	size: 206
	**type**: "text/**plain**"
}

Response after uploading:

{
	bucket: "bucket-name"
	key: "1570638118950_test-file.plain"
	location: "https://publisher-documents-upload.s3-us-east-2.amazonaws.com/1570638118950_test-file.**plain**"
	status: 204
}

But the output should be as location: "https://publisher-documents-upload.s3-us-east-2.amazonaws.com/1570638118950_test-file.**txt**"

Maybe because of the below line of code written in react-aws-s3.ts
const fileName: string = `${newFileName || shortId.generate()}.${fileExtension}`;

This also happens for other file types too like _excel_

**Comment by Developer-Amit** [comment]
Hi,
Did you tried passing your own filename in parameter newFileName

Ie.
const newFileName = 'test-file.txt';
 
ReactS3Client
    .uploadFile(file, newFileName)
    .then(data => console.log(data))
    .catch(err => console.error(err))

**Comment by twenshin** [comment]
I'm also getting this behaviour.
I'm passing the original filename in `newFileName` and still getting mime type appended after file extension.

```
const ReactS3Client = new S3(config);
Array.from(files).forEach(file => {
    ReactS3Client.uploadFile(file, file.name).then((data) => {
        ...
    }).catch(() => {
        ...
    });
});
```
where `files` are `FileList` object with some files i want to upload.

**Update:**
Also tried to upload a file object with fully custom filename (dict.json), got dict.json.json in bucket.

**Comment by ismaelash** [comment]
I create a fix for this problem: https://github.com/ismaelash/aws-s3-reactjs

**Comment by StevenCreates** [comment]
@twenshin 
I also had this problem, so I ended up passing my own file name.
https://github.com/StevenCreates/react-file-aws/blob/7b117416c0005fa1d58daef98b3417e71c12e743/src/components/Upload.js#L9

Here is how I solved it in my code

**Comment by Programmusic** [comment]
Hello - to add to the discussion - I have also been having this problem with CSV files adding the mime type. Steven Crates solution does not work for me as it is uploading the mime type instead of .csv

This is causing a problem for me because I have a Lambda listing for event notifications with a .csv suffix. I'm hoping maybe @levdad has solved this for us?

**Comment by Developer-Amit** [comment]
I'm adding fix and publishing new version.

---
Regards

Amit Mishra

Lead Software Engineer (Fullstack Technology Lead)
Mobile/Whatsapp- +919584227532
Skype - developer_amit
Website - www.developeramitmishra.com

**Comment by Developer-Amit** [comment]
Try to update version 1.4.0

**Comment by Programmusic** [comment]
Thank Amit - works perfectly now. You are a star.

**Comment by Developer-Amit** [comment]
Thank you so much.


---
Regards

Amit Mishra

Lead Software Engineer (Fullstack Technology Lead)
Mobile/Whatsapp- +919584227532
Skype - developer_amit
Website - www.developeramitmishra.com
