### ISSUE TITLE
Multiple files upload support?

### ISSUE THREAD

**Issue by tralawar** [Developer-Amit/react-aws-s3#6]
Does this support multiple files at once? can you provide an example in the read me if so? Thanks

**Comment by Developer-Amit** [comment]
What happens if you run the upload method in loop with promise for your each files.
You will get all files S3 urls one by one.

**Comment by tralawar** [comment]
Yes, I found a solution using that method and posting the question to you.
Looks like I will get to practice with them. Is there a way to do it with
one call to S3? Thank you for your work. It was clear and easy to implement.

**Comment by tralawar** [comment]
Pushing promises to an `array` and then using `Promise.all(array)`  works great thanks again.

**Comment by Developer-Amit** [comment]
Nice, I was doing same. Awesome.

---
Regards

Amit Mishra

Senior Software Engineer (Full stack Web)
Mobile - +919584227532
Skype - developer_amit
Website - www.developeramitmishra.com

**Comment by ithustle** [comment]
> Pushing promises to an `array` and then using `Promise.all(array)` works great thanks again.

If I were sending large files like a song files? 10 MB at least, Can I use the same? @Developer-Amit

**Comment by Developer-Amit** [comment]
Yes This should work fine.


---
Regards

Amit Mishra

Lead Software Engineer (Fullstack Technology Lead)
Mobile/Whatsapp- +919584227532
Skype - developer_amit
Website - www.developeramitmishra.com
