### ISSUE TITLE
Can't pass ACL parameter with react-aws-s3. Because of this I can't access private bucket

### ISSUE THREAD

**Issue by ayazpathan** [Developer-Amit/react-aws-s3#7]
Tried to access that but I couldn't facing error 403

Got return data shown below

**body**: (...)
**bodyUsed**: false
**headers**: Headers {}
**ok**: false
**redirected**: false
**status**: 403
**statusText**: "Forbidden"
**type**: "cors"

**Comment by Developer-Amit** [comment]
In the npm page there is a link for CORS setup instructions on your AWS
bucket, please make sure you have allowed permission to write data into
your bucket.
Thanks

---
Regards

Amit Mishra

Senior Software Engineer (Full stack Web)
Mobile - +919584227532
Skype - developer_amit
Website - www.developeramitmishra.com

**Comment by ayazpathan** [comment]
My AWS developer said the bucket is private, so you can't access directly. He said pass **ACL** as **private**, but I can see no such option to pass **acl** in your package. Can you help me out of this? Waiting for your reply brother.

**Comment by Developer-Amit** [comment]
Yes sure, I will help how to do setup Cors, reach to me on Skype
developer_amit you will need to login AWS console only you can do from
there.


---
Regards

Amit Mishra

Senior Software Engineer (Full stack Web)
Mobile - +919584227532
Skype - developer_amit
Website - www.developeramitmishra.com

**Comment by harsh4870** [comment]
any update here, facing same error would it be possible to share the solution ?
