### ISSUE TITLE
Delete Not working

### ISSUE THREAD

**Issue by Shayan-wave** [Developer-Amit/react-aws-s3#8]
I am getting an error msg when I am try to delete some thing from the s3 but upload is working fine

**Comment by Developer-Amit** [comment]
Can you please send here full errors log and screenshot.

---
Regards

Amit Mishra

Lead Software Engineer (Fullstack Technology Lead)
Mobile/Whatsapp- +919584227532
Skype - developer_amit
Website - www.developeramitmishra.com

**Comment by Shayan-wave** [comment]
![React-aws-s3_Error](https://user-images.githubusercontent.com/64144099/95417845-a92a7680-0953-11eb-9b5e-9b3cc1ebfb98.PNG) 
This is response I am getting in return

**Comment by Developer-Amit** [comment]
Hello @Shayan-wave Thank you for providing the error details you are facing. 
I personally have gone through every Test case for deleting files from the Bucket and it seems passed all Test and working as per expectations. 

In the Your case I found you have the CORS problem in your AWS s3 Bucket Policy 

you need to follow the Link Already available on the NPM page - http://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html

And update your Bucket policy in the correct way to provide them access to delete the files. 

If you are not good at AWS services contact your AWS cloud engineer and ASK them to allow the CORS in the bucket for the DELETE method. 
Hope this information will help you.
